site_name: inventáře.cz – nápověda a seznam zkratek

copyright: "© 2025 Státní oblastní archiv v Plzni · <a href='https://www.soaplzen.cz'>soaplzen.gov.cz</a> · <a href='https://www.inventare.cz'>inventare.cz</a> · <a href='https://www.portafontium.eu'>portafontium.eu</a>"

theme:
  name: material
  language: cs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - content.code.copy
  palette:
    scheme: default
    toggle:
      icon: material/weather-night
      name: Přepnout režim

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
      lang: [en, cs]
      separator: '[\s\-]+'

extra:
  social:
    - icon: fontawesome/solid/circle-info
      link: https://www.inventare.cz
      name: inventare.cz
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/SOAvPlzni
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/archivplzen
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/SOAvPlzni
  generator: false
  nav:
    - icon: material/help-circle
      title: Nápověda
    - icon: material/order-alphabetical-ascending
      title: Zkratky
    - icon: material-arrow-u-right-top-bold
      title: ZPĚT na inventáře.cz
    - icon: material-sitemap
      title: Archivní soubory
    - icon: material-file-document-multiple
      title: Archiválie
    - icon: material-label
      title: Přístupové body
    - icon: material-book-information-variant
      title: Vysvětlivky
      
nav:
  - Úvod: index.md
  - Nápověda: 
    - Vysvětlivky: help/index.md
    - Jak na webu vyhledávat: help/searching.md
    - Úvodní strana webu: help/homepage.md
    - Sekce: 
      - Sekce – úvod: sections/index.md
      - Společné prvky sekcí: sections/shared.md
      - Archivní soubory: sections/section-fund.md
      - Archiválie: sections/section-archdesc.md
      - Přístupové body: sections/section-entity.md
    - Vysvětlivky: help/glossary.md
  - Zkratky:
    - 0–9: abbreviations/index.md
    - A, B, C, Č: abbreviations/a-c.md
    - D, E, F, G, H: abbreviations/d-h.md
    - CH, I, J, K: abbreviations/ch-k.md
    - L, M, N: abbreviations/l-n.md
    - O: abbreviations/o.md
    - P, R, Ř: abbreviations/p-r.md
    - S, Š: abbreviations/s.md
    - T, U, V: abbreviations/t-v.md
    - Y, Z, Ž: abbreviations/y-z.md
  - ↻ ZPĚT na inventáře.cz: https://www.inventare.cz

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

strict: false
use_directory_urls: true
