site_name: Inventare Help
repo_url: https://github.com/PetrKocourek/help.inventare.cz
edit_uri: edit/main/docs

theme:
  name: material
  language: cs
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    scheme: default
    toggle:
      icon: material/weather-night
      name: Přepnout režim

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search

nav:
  - Nápověda:
      - Úvod: help/index.md
      - Jak vyhledávat: help/searching.md
      - Úvodní strana: help/home.md
      - Sekce: help/sections.md
  - Vysvětlivky: glossary/index.md
  - Zkratky:
      - Rozcestník: abbreviations/index.md
      - 0–9: abbreviations/0-9.md
      - A,B,C,Č: abbreviations/a-c.md
      - D,E,F,G,H: abbreviations/d-h.md
      - CH,I,J,K: abbreviations/ch-k.md
      - L,M,N: abbreviations/l-n.md
      - O: abbreviations/o.md
      - P,R: abbreviations/p-r.md
      - S: abbreviations/s.md
      - T,U,V: abbreviations/t-v.md
      - Y,Z,Ž: abbreviations/y-z.md

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

strict: false
use_directory_urls: true
